name: Pull Request - Dev

on:
  pull_request:
    types: [opened, synchronize]

    branches:
      - staging

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Setup Node JS
      uses: actions/setup-node@v1
      with:
        node-version: "11.5.0"
        
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test -- --silent --verbose
  
  flow:
    name: Flow Check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Setup Node JS
      uses: actions/setup-node@v1
      with:
        node-version: "11.5.0"
        
    - name: Install dependencies
      run: npm ci

    - name: Run flow
      run: npm run flow

  build:
    name: Run Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Setup Node JS
      uses: actions/setup-node@v1
      with:
        node-version: "11.5.0"
        
    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build
